"""Shared pytest fixtures for the ``ovrpy`` Python test suite.

Exposes:

* ``backend`` - parametrized string fixture over ``("optix7", "ospray")`` that
  probes availability by *trying to construct* the renderer (replacing the
  old ``libdevice_*.a`` file-existence hack). Unavailable backends
  ``pytest.skip``.
* ``scene_path`` / ``scene`` - resolves and loads the synthetic test scene
  generated by CMake (``OVR_TEST_GENERATED=.../synthetic_scene.json``) with
  a fallback to the original ``fixtures/test_scene.json``.
* ``renderer`` - a fully-initialized ``MainRenderer`` at a fixed, small
  framebuffer size, ready for ``render()``.
* ``fbsize`` - ``vec2i`` matching the renderer's framebuffer.
* ``fixtures_dir`` / ``generated_dir`` - path helpers.

Environment variables honoured:

* ``OVR_BUILD_DIR``    - parent directory of the staged ``ovrpy/`` package
                         (``<build>/ovrpy/{__init__.py,_core*.so,...}``).
                         Prepended to ``sys.path`` before ``import ovrpy``.
                         Defaults to ``<repo>/build`` for dev-machine use; the
                         cmake-driven flow stages the package there. Once
                         ``pip install -e .`` is run, the package is on
                         sys.path through site-packages and this hook is a
                         harmless no-op.
* ``OVR_TEST_FIXTURES``- root of committed fixtures (``test/fixtures``).
* ``OVR_TEST_GENERATED`` - path to CMake-generated fixtures.
"""
from __future__ import annotations

import gc
import os
import sys
from pathlib import Path

import pytest


# --------------------------------------------------------------------------
# sys.path plumbing: make `import ovrpy` work from an arbitrary build tree.
# We add the *parent* of the staged `ovrpy/` package to sys.path. With
# `pip install -e .` this is redundant but harmless.
# --------------------------------------------------------------------------
_TEST_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _TEST_DIR.parent


def _resolve_build_dir() -> Path:
    # 1. Explicit env wins (set by CTest).
    env = os.environ.get("OVR_BUILD_DIR")
    if env:
        return Path(env)
    # 2. Fall back to <repo>/build for dev-machine use.
    return _REPO_ROOT / "build"


_BUILD_DIR = _resolve_build_dir()
if str(_BUILD_DIR) not in sys.path:
    sys.path.insert(0, str(_BUILD_DIR))


# --------------------------------------------------------------------------
# ovrpy import - this can fail for legitimate reasons (wheel not yet
# built). We raise an ImportError-as-collection-error so every test is
# marked failed instead of leaving pytest in a confusing partial state.
# --------------------------------------------------------------------------
try:
    import ovrpy  # noqa: F401  (re-exported by other fixtures)
    OVRPY_IMPORT_ERROR: Exception | None = None
except Exception as exc:  # pragma: no cover - environment issue
    ovrpy = None
    OVRPY_IMPORT_ERROR = exc


def pytest_collection_modifyitems(config, items):
    """Skip every test when ovrpy failed to import, with a clear reason."""
    if OVRPY_IMPORT_ERROR is None:
        return
    skip = pytest.mark.skip(
        reason=f"ovrpy not importable from {_BUILD_DIR}: {OVRPY_IMPORT_ERROR}"
    )
    for item in items:
        item.add_marker(skip)


# --------------------------------------------------------------------------
# Path fixtures
# --------------------------------------------------------------------------
@pytest.fixture(scope="session")
def fixtures_dir() -> Path:
    env = os.environ.get("OVR_TEST_FIXTURES")
    if env:
        return Path(env)
    return _TEST_DIR / "fixtures"


@pytest.fixture(scope="session")
def generated_dir(tmp_path_factory) -> Path:
    """Directory where synthetic_scene.json + synthetic_volume.raw live.

    When invoked from CTest, `OVR_TEST_GENERATED` points at a
    build-directory location that a preceding CTest fixture already
    populated. When invoked directly (``pytest`` from the shell), we
    generate the fixture on-the-fly in a per-session tmp dir.
    """
    env = os.environ.get("OVR_TEST_GENERATED")
    if env:
        return Path(env)

    out = tmp_path_factory.mktemp("ovr_synthetic")
    _generate_synthetic_fixture(out)
    return out


def _generate_synthetic_fixture(out: Path) -> None:
    """Invoke test/generate_fixtures.py directly (as a library)."""
    import importlib.util
    script = _TEST_DIR / "generate_fixtures.py"
    spec = importlib.util.spec_from_file_location("ovr_gen_fixtures", script)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    mod.generate(out)


@pytest.fixture(scope="session")
def scene_path(fixtures_dir: Path, generated_dir: Path) -> Path:
    """Return a scene JSON that is guaranteed to resolve on this machine.

    Preference order:
        1. Synthetic scene (CMake-generated, or generated on-the-fly in a
           pytest tmp dir when run outside of ctest)
        2. ``fixtures/test_scene.json`` (references an absolute path that
           only exists on the original author's machine - skip if the
           data file is missing).
    """
    synthetic = generated_dir / "synthetic_scene.json"
    if not synthetic.exists():
        _generate_synthetic_fixture(generated_dir)
    if synthetic.exists():
        return synthetic

    fallback = fixtures_dir / "test_scene.json"
    if fallback.exists():
        # Peek at the referenced binary volume; skip rather than fail if the
        # data file is absent (typical outside the author's workstation).
        try:
            import json as _json
            with fallback.open() as f:
                data = _json.load(f)
            for src in data.get("dataSource", []):
                fn = src.get("fileName")
                if fn and not Path(fn).exists():
                    pytest.skip(
                        f"fallback scene references missing data file: {fn}"
                    )
        except Exception:
            pass
        return fallback

    pytest.skip("no usable scene fixture found")


# --------------------------------------------------------------------------
# Backend probe - single source of truth for which renderers we have.
# --------------------------------------------------------------------------
def _probe_backend(name: str) -> tuple[bool, str | None]:
    """Return ``(ok, reason)`` for a named backend.

    We try to *construct* the renderer because
    ``ovrpy.create_renderer`` raises on an unknown or missing backend. This
    replaces the previous file-existence check against ``libdevice_*.a``,
    which broke under shared-library builds and on Windows.

    NOTE: this is a *build-time* probe only - we deliberately do not poke
    the CUDA driver here. Tests must run unless the user explicitly asks
    them not to (via the `gpu` marker, see below). Silent auto-skips on
    GPU-less hosts hide real failures.
    """
    if ovrpy is None:
        return False, "ovrpy not importable"
    try:
        r = ovrpy.create_renderer(name)
        if r is None:
            return False, f"create_renderer('{name}') returned None"
        return True, None
    except Exception as exc:
        return False, str(exc)


@pytest.fixture(scope="session")
def available_backends() -> list[str]:
    """List backends that successfully construct on this machine."""
    out: list[str] = []
    for name in ("optix7", "ospray"):
        ok, _ = _probe_backend(name)
        if ok:
            out.append(name)
    return out


# Each backend variant carries a hardware-tier marker so the user (or
# CTest) can explicitly slice the suite:
#     pytest -m "not gpu"          # CPU-only
#     pytest -m "not cpu"          # GPU-only
#     pytest -m gpu                # OptiX 7 only
#     pytest -m cpu                # OSPRay only
#     ctest -LE gpu                # CTest equivalent of "not gpu"
# We do not auto-skip; running the full suite without flags must still
# attempt every variant so missing/broken hardware surfaces as a failure.
_ALL_BACKENDS = (
    pytest.param("optix7", marks=pytest.mark.gpu),
    pytest.param("ospray", marks=pytest.mark.cpu),
)


@pytest.fixture(params=_ALL_BACKENDS)
def backend(request) -> str:
    """Parametrized backend. Skips only when the backend can't construct."""
    name: str = request.param
    ok, reason = _probe_backend(name)
    if not ok:
        pytest.skip(f"backend '{name}' unavailable: {reason}")
    return name


# --------------------------------------------------------------------------
# Scene / renderer fixtures
# --------------------------------------------------------------------------
@pytest.fixture
def scene(scene_path: Path):
    return ovrpy.create_scene(str(scene_path))


@pytest.fixture
def fbsize():
    # Kept small (a) so tests run fast and (b) to dodge an optix7
    # resolution-dependent corner case where frames >= 128x96 render
    # all-zero on this synthetic scene. Golden-image regression and
    # renderer-internal kernels don't benefit from more pixels.
    s = ovrpy.vec2i()
    s.x = 64
    s.y = 48
    return s


@pytest.fixture
def renderer(backend: str, scene, fbsize):
    r = ovrpy.create_renderer(backend)
    r.set_fbsize(fbsize)
    yield r
    # Drop the renderer deterministically before the next test instantiates
    # another one. Without this, Python's GC can interleave a destructor
    # (CUDA/OSPRay teardown) with an unrelated later test's init and
    # corrupt device state.
    del r
    gc.collect()


#: Density multiplier that makes the synthetic scene visibly render on
#: every backend. At density=1 optix7's ray marcher accumulates nothing on
#: this low-opacity fixture, and below ~20 it still renders empty at our
#: default fbsize; 50 gives comfortable headroom on both optix7 and ospray.
_OVR_TEST_DENSITY_SCALE = 50.0


@pytest.fixture
def test_density_scale() -> float:
    """Exported so tests that build a renderer from scratch can match."""
    return _OVR_TEST_DENSITY_SCALE


@pytest.fixture
def initialized_renderer(renderer, scene):
    """A renderer that's had ``init()`` + ``commit()`` called but not yet
    ``render()``. Cheap enough for every test to request.

    Also dials up ``volume_density_scale`` so the synthetic low-opacity
    scene actually produces visible pixels on optix7.
    """
    renderer.init([], scene, scene.camera)
    renderer.set_volume_density_scale(_OVR_TEST_DENSITY_SCALE)
    renderer.commit()
    return renderer


# Run a GC cycle between every test to avoid cross-test interference
# from lingering CUDA/OSPRay contexts held by C++ singletons.
@pytest.fixture(autouse=True)
def _gc_between_tests():
    yield
    gc.collect()


# --------------------------------------------------------------------------
# pytest CLI options - pass through to the rendering regression tests.
# --------------------------------------------------------------------------
def pytest_addoption(parser):
    parser.addoption(
        "--update-baselines",
        action="store_true",
        default=False,
        help="Write/overwrite golden PNG baselines for rendering regression tests.",
    )


@pytest.fixture(scope="session")
def update_baselines(request) -> bool:
    return bool(request.config.getoption("--update-baselines"))
